site_name: CMS Tracker DPG - Software Knowledge Base
nav:
  - Home &#127968;: index.md
  - basic-concepts.md
  - CMSSW &#128128;:
      - cmssw/introduction.md
      - Tools &#128295;: cmssw/tools.md      
      - Workflows &#128200;:
          - cmssw/working-with-cmssw/workflows/overview.md
          - cmssw/working-with-cmssw/workflows/usage.md
          - cmssw/working-with-cmssw/workflows/history.md
      - Working with CMSSW:
          - Developing: cmssw/working-with-cmssw/software.md
          - cmssw/working-with-cmssw/gpu-machines.md
          - cmssw/working-with-cmssw/proposing-changes.md                        
      - Documentation on CMSSW modules:
          - CPU &#129704;:
              - cmssw/cpu/index.md
              - Data Formats:
                  - PixelDigi:
                      - cmssw/cpu/PixelDigi-overview.md                  
                  - SiPixelCluster:
                      - cmssw/cpu/SiPixelCluster-overview.md
              - PixelThresholdClusterizer:
                  - cmssw/cpu/PixelThresholdClusterizer-overview.md
                  - cmssw/cpu/PixelThresholdClusterizer-copytobuffer.md
          - GPU &#128396;&#65039;:
              - cmssw/gpu/overview.md
              - gpuClustering.h:
                  - cmssw/gpu/gpuClustering-overview.md
                  - cmssw/gpu/gpuClustering-findClus.md
                  - cmssw/gpu/gpuClustering-countModules.md
              - gpuCalibPixel.h:
                  - cmssw/gpu/calibPixels.md
      - cmssw/build-types.md                  
      - Extra Resources:
          - Angela's GPU primer:
              - czangela-tutorial/index.md
              - Week 1:
                  - czangela-tutorial/weeks/week01_material.md
                  - czangela-tutorial/weeks/week01_exercises.md
              - Week 2:
                  - czangela-tutorial/weeks/week02_material.md
                  - czangela-tutorial/weeks/week02_exercises.md                                    
              - Week 3:
                  - czangela-tutorial/weeks/week03_material.md
          - cmssw/extra-resources/extra-gpu.md
          - cmssw/extra-resources/extra-cmssw.md          
  - Certhelper (a.k.a Certifier) &#9989;:
      - certhelper/introduction.md
      - Developing:
          - Branches: certhelper/developing/branches.md
      - Deploying:
          - Deployments: certhelper/deploying/deployments.md
  - MLPlayground &#129528;:
      - mlplayground/introduction.md
  

theme:
  name: material
  features:
    - navigation.sections
    - content.tabs.link
    - content.code.annotate
  favicon: img/favicon.ico
  logo: img/favicon.ico
  icon:
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html

plugins:
  - section-index
  - search

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra:
  analytics:
    provider: google
    property: G-ZZ8D6PMHP5
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
