site_name: CMS Tracker DPG - knowledge transfer workshop
nav:
  - Home: index.md
  - Connecting to GPU machines:
    - getting-started/index.md
  - Knowledge transfer material:
    - daily/day01-02.md
  #- GPU basics: learn-gpu-basics.md
  #- Workflows and profilig:
  #  - workflows/index.md
  #  - Page 1: workflows/profiling.md
theme:
  name: material
  features:
    - navigation.sections
markdown_extensions:
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg