site_name: CMS Tracker DPG - Software Knowledge Base
repo_url: https://github.com/CMSTrackerDPG/cms-tkdpg-software-knowledge-transfer
edit_uri: edit/master/docs/
nav:
  - Home &#127968;: index.md
  - basic-concepts.md
  - CMSSW &#128128;:
      - cmssw/introduction.md
      - cmssw/working-with-cmssw/setup.md
      - cmssw/build-types.md                        
      - cmssw/working-with-cmssw/proposing-changes.md                                        
      - Tools &#128295;: cmssw/tools.md
      - Debugging: cmssw/debugging.md
      - Workflows &#128200;:
          - cmssw/workflows/overview.md
          - cmssw/workflows/usage.md
          - cmssw/workflows/history.md
      - Documentation &#128216;:
          - Pixel-Local Reconstruction:
              - cmssw/pixel-local/overview.md
              - Dataflow:
                  - cmssw/pixel-local/pixel.md
              - CPU &#129704;:
                  - cmssw/pixel-local/cpu/index.md
                  - Data Formats:
                      - DetSetVector:
                          - cmssw/pixel-local/cpu/DetSetVector-overview.md
                      - PixelDigi:
                          - cmssw/pixel-local/cpu/PixelDigi-overview.md                  
                      - SiPixelCluster:
                          - cmssw/pixel-local/cpu/SiPixelCluster-overview.md
                  - PixelThresholdClusterizer:
                      - cmssw/pixel-local/cpu/PixelThresholdClusterizer-overview.md
                      - cmssw/pixel-local/cpu/PixelThresholdClusterizer-copytobuffer.md
                  - SiPixelArrayBuffer:
                      - cmssw/pixel-local/cpu/SiPixelArrayBuffer-overview.md
              - GPU &#128396;&#65039;:
                  - cmssw/pixel-local/gpu/index.md
                  - Data Formats:
                      - SiPixelDigisCUDA:
                          - cmssw/pixel-local/gpu/SiPixelDigisCUDA.md
                      - SiPixelDigisCUDASOAView:
                          - cmssw/pixel-local/gpu/SiPixelDigisCUDASOAView.md
                      - SiPixelClustersCUDA:
                          - cmssw/pixel-local/gpu/SiPixelClustersCUDA.md                                            
                  - SiPixelRawToClusterCUDA.cc:
                      - cmssw/pixel-local/gpu/SiPixelRawToClusterCUDA-overview.md
                      - SiPixelRawToClusterGPUKernel.h:
                          - cmssw/pixel-local/gpu/SiPixelRawToClusterGPUKernel-overview.md
                          - gpuCalibPixel.h:
                              - cmssw/pixel-local/gpu/gpuCalibPixel.md
                              - calibDigis:
                                  - cmssw/pixel-local/gpu/gpuCalibPixel-calibDigis.md                  
                          - gpuClustering.h:
                              - cmssw/pixel-local/gpu/gpuClustering-overview.md
                              - cmssw/pixel-local/gpu/gpuClustering-countModules.md
                              - cmssw/pixel-local/gpu/gpuClustering-findClus.md                  
                  - SiPixelDigisSoAFromCUDA:
                      - cmssw/pixel-local/gpu/SiPixelDigisSoAFromCUDA-overview.md
                  - SiPixelDigisClustersFromSoA.cc:                  
                      - cmssw/pixel-local/gpu/SiPixelDigisClustersFromSoA-overview.md                  
      - Extra Resources:
          - general/cmssw/extra-cmssw.md
      - FAQ &#10067;:
          - cmssw/working-with-cmssw/faq.md
  - Certhelper (a.k.a Certifier) &#9989;:
      - certhelper/introduction.md
      - Developing &#129489;&#8205;&#128187;:
          - Branches: certhelper/developing/branches.md
      - Deploying &#128674;:
          - certhelper/deploying/overview.md
          - Guide: certhelper/deploying/guide.md
          - Deployments: certhelper/deploying/deployments.md
      - Connectivity &#128279;: certhelper/connectivity.md
      - Apps &#129513;:
          - dqmhelper:
              - certhelper/apps/dqmhelper/overview.md
          - certifier:
              - certhelper/apps/certifier/overview.md
              - Views:
                  - CertifyView: certhelper/apps/certifier/views/certify.md
                  - badReason: certhelper/apps/certifier/views/badreason.md
                  - addBadReason: certhelper/apps/certifier/views/addbadreason.md
              - Query: certhelper/apps/certifier/query.md
          - listruns:
              - certhelper/apps/listruns/overview.md              
              - Views:
                  - UpdateRunView: certhelper/apps/listruns/views/updaterun.md
          - addrefrun:
              - certhelper/apps/addrefrun/overview.md
              - Views:
                  - update_refruns_info: certhelper/apps/addrefrun/views/update_refruns_info.md
          - oms:
              - certhelper/apps/oms/overview.md
              - Models: certhelper/apps/oms/models.md
          - omsapi:
              - certhelper/apps/omsapi/overview.md
          - shiftleader:
              - certhelper/apps/shiftleader/overview.md
              - Views:
                  - ShiftLeader Report: certhelper/apps/shiftleader/views/shiftleader_report.md
                  - ShiftLeader Report Presentation: certhelper/apps/shiftleader/views/shiftleader_report_presentation.md                    
              - Obsolete code:
                  - certhelper/apps/shiftleader/obsolete.md
          - home:
              - certhelper/apps/home/overview.md
          - remotescripts:
              - certhelper/apps/remotescripts/overview.md
              - certhelper/apps/remotescripts/configuration.md
              - Consumers:
                  - ScriptOutputConsumer:
                      - certhelper/apps/remotescripts/consumers/script_output.md
              - Views:
                  - ScriptExecution:
                      - certhelper/apps/remotescripts/views/script_execution.md
          - summary:
              - certhelper/apps/summary/overview.md
              - Models:
                  - certhelper/apps/summary/models.md
              - Views:
                  - SummaryView:
                      - certhelper/apps/summary/views/SummaryView.md
      - Documentation &#128216;:
          - certhelper/docs.md                      
              
  - MLPlayground &#129528;:
      - mlplayground/introduction.md
      - Configuration:
          - mlplayground/config.md
      - Deploying &#128674;:
          - Deployments: mlplayground/deploying/deployments.md      
      - Connectivity &#128279;: mlplayground/connectivity.md
      - Apps &#129513;:
          - histogram_file_manager:
              - mlplayground/apps/histogram_file_manager/overview.md
              - Models:
                  - mlplayground/apps/histogram_file_manager/models.md
              - Management Commands:
                  - mlplayground/apps/histogram_file_manager/management.md
              - API:
                  - mlplayground/apps/histogram_file_manager/api.md
          - histograms:
              - mlplayground/apps/histograms/overview.md
              - Models:
                  - mlplayground/apps/histograms/models.md
      - Documentation &#128216;:
          - mlplayground/docs.md
      - FAQ &#10067;:
          - mlplayground/faq.md
  - General documentation:
      - SSH:
          - Tunnelling:
              - general/ssh/tunnel.md
          - Mounting remote filesystems:
              - general/ssh/mounting_remote.md
      - CUDA and GPU development:
          - Angela's GPU primer:
              - czangela-tutorial/index.md
              - Week 1:
                  - czangela-tutorial/weeks/week01_material.md
                  - czangela-tutorial/weeks/week01_exercises.md
              - Week 2:
                  - czangela-tutorial/weeks/week02_material.md
                  - czangela-tutorial/weeks/week02_exercises.md                                    
              - Week 3:
                  - czangela-tutorial/weeks/week03_material.md
          - general/gpu/extra-gpu.md
          - general/gpu/cern-resources.md

      - Django:
          - general/django/overview.md
          - Setup:
              - general/django/setup/overview.md
          - Database:
              - Exporting/Importing data:
                  - general/django/database/exporting_importing.md

      - Development General:
          - Versioning:
              - general/development/versioning.md
          
      - Openshift:
          - Resources:
              - general/openshift/resources.md
          - Routes:
              - general/openshift/routes.md
theme:
  name: material
  features:
    - navigation.sections
    - content.tabs.link
    - content.code.annotate
    - content.action.edit
    - content.action.view    
  favicon: img/favicon.ico
  logo: img/favicon.ico
  # icon:
  #   admonition:
  #     note: fontawesome/solid/sticky-note
  #     abstract: fontawesome/solid/book
  #     info: fontawesome/solid/info-circle
  #     tip: fontawesome/solid/bullhorn
  #     success: fontawesome/solid/check
  #     question: fontawesome/solid/question-circle
  #     warning: fontawesome/solid/exclamation-triangle
  #     failure: fontawesome/solid/bomb
  #     danger: fontawesome/solid/skull
  #     bug: fontawesome/solid/robot
  #     example: fontawesome/solid/flask
  #     quote: fontawesome/solid/quote-left

markdown_extensions:
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde  
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html

plugins:
  - section-index
  - search

# extra:
#   consent:
#     title: Cookie consent
#     description: >- 
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of our documentation and whether users
#       find what they're searching for. With your consent, you're helping us to
#       make our documentation better.
# extra:
#   analytics:
#     provider: google
#     property: G-ZZ8D6PMHP5
#     feedback:
#       title: Was this page helpful?
#       ratings:
#         - icon: material/heart
#           name: This page was helpful
#           data: 1
#           note: >-
#             Thanks for your feedback!
#         - icon: material/heart-broken
#           name: This page could be improved
#           data: 0
#           note: >- 
#             Thanks for your feedback! Help us improve this page by
#             using our <a href="..." target=_blank>feedback form</a>.
